name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      # - name: Run black
      #   run: tox -e black
      # - name: Run isort
      #   run: tox -e isort
      - name: Run pylint
        run: tox -e pylint
      - name: Run mypy
        run: tox -e mypy
      - name: Run pytest
        run: tox -e py
      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.10'
        run: tox -e coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Check docs
        run: tox -e docs

  publish:
    needs: [test, docs]  # only run if previous jobs are successful
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a source tarball
        run: python -m build --sdist --outdir dist/ .
      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
